llm_model = "qwen3-coder:30b"
llm_vision_model = "llama3.2-vision:11b"
img_to_html_model="HuggingFaceM4/VLM_WebSight_finetuned"
embedding_model = "all-MiniLM-L6-v2"
gpu_server_llm = "Qwen/Qwen2-VL-7B-Instruct-AWQ"